# GitHub Dark theme
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#bc8cff"
      - bold
    inactiveBorderColor:
      - "#8b949e"
    optionsTextColor:
      - "#58a6ff"
    selectedLineBgColor:
      - "#161b22"
    cherryPickedCommitBgColor:
      - "#76e3ea"
    cherryPickedCommitFgColor:
      - "#58a6ff"
    unstagedChangesColor:
      - "#ff7b72"
    defaultFgColor:
      - "#e6edf3"
    searchingActiveBorderColor:
      - "#d29922"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

os:
  editCommand: 'nvim'
